In [2]:
import numpy as np 
a = np.array([5,6,9])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim     # property to use the dimensions

2

In [5]:
a.itemsize

8

In [6]:
a.dtype

dtype('int64')

In [7]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

a.itemsize

In [8]:
a.itemsize

8

In [9]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
a.size  # total number of the elementss

6

In [ ]:
a.shape      #width and height

(3, 2)

In [24]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
b = range(5)
b

range(0, 5)

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,6,2)        # last 2 is step that count the numbers

array([1, 3, 5])

In [21]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
a.shape

(3, 2)

In [25]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [31]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [32]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a.min()

np.int64(1)

In [35]:
a.max ()

np.int64(6)

In [36]:
a.sum(axis=0)

array([ 9, 12])

In [5]:
np.sqrt(a)

NameError: name 'np' is not defined

In [38]:
np.std(a)

np.float64(1.707825127659933)

In [46]:
import numpy as np

d = np.array([[1, 2], [3, 4]])
c = np.array([[5, 6], [7, 8]])

# Displaying the array d
print(d)


TypeError: 'list' object is not callable

In [ ]:
# Pandas -> Process of cleaning messy Data is called data munging OR data wrangling 